theme: jekyll-theme-slate
title: Shaidy Advice's homepage
description: Coming soon!

# Social links
twitter_username: yourusername
linkedin_username: yourusername

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
